### ISSUE TITLE
Inconsistent executable path handling breaks tasks on Windows

### ISSUE THREAD

**Issue by brandon-avantus** [avantus-tech/pyproject-runner#1]
Tasks attempting to run the python from the project's virtual environment might resolve the wrong executable due to  known [inconsistent behavior](https://docs.python.org/3/library/subprocess.html#subprocess.Popen) in `subprocess.Popen()`.

## Steps to reproduce

Given the following tasks in *pyproject.toml*:
```toml
# pyproject.toml
[project]
name = "myproject"
# ...

[dependency-groups]
dev = ["pyproject-runner == 0.2.1"]
# ...

[tool.pyproject-runner.tasks]
run = "python -m myproject"
```

1. Install the shim: `uv tool install pyproject-runner-shim`
2. Run the project's *run* task using the shim: `rr run`

## Observed behavior

Because *uv* adds the path of the shim's virtual environment to **PATH**, when *pyproject-runner* finds the python executable associated with the shim and not the project, execution of the module fails with an error like the following:
```
C:\Users\User\AppData\Roaming\uv\python\cpython-3.10.16-windows-x86_64-none\python.exe: Error while finding module specification for 'myproject' (ModuleNotFoundError: No module named 'myproject')
```

## Expected behavior

The python interpreter associated with the project is found and used so that the module is also found and executed.

## Environment

Affected systems: Windows
Git revision: 31e45fecd
Release: 0.2.1 (pre-release)
